# Generated by Django 5.0.4 on 2024-04-09 13:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='only_medias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'avi', 'mpeg4', 'mkv', 'pdf', 'doc', 'docx', 'gif'])], verbose_name='File')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('gif', 'Gif'), ('other', 'Other')], max_length=10, verbose_name='File Type')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='MediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_banner_text', models.TextField(verbose_name='Our Banner Text')),
                ('product_page_back_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media', verbose_name='Product Page Back Image')),
            ],
            options={
                'verbose_name': 'Media Settings',
                'verbose_name_plural': 'Media Settings',
            },
        ),
    ]
